//! Integration tests comparing rustfoil-solver viscous results with XFOIL.
//!
//! These tests validate that the viscous solver integration with rustfoil-inviscid
//! produces results matching XFOIL's VISCAL.
//!
//! Reference data is generated by `scripts/extract_viscous_reference.py`.

use serde::Deserialize;
use std::fs::File;
use std::io::BufReader;
use std::path::Path;

// Import the solver types
use rustfoil_solver::viscous::{
    setup_from_coords, interpolate_stagnation, compute_arc_lengths, ViscousSetupResult,
};

/// Reference data structure matching viscous_ref.json
#[derive(Debug, Deserialize)]
struct ViscousReference {
    test: String,
    source: String,
    n_panels: usize,
    reynolds: f64,
    mach: f64,
    ncrit: f64,
    airfoil: String,
    #[serde(default)]
    stagnation_base: Option<StagnationRef>,
    #[serde(default)]
    bl_setup_base: Option<BlSetupRef>,
    cases: Vec<ViscousCase>,
}

#[derive(Debug, Deserialize)]
struct StagnationRef {
    #[serde(rename = "ist")]
    pub ist: usize,
    #[serde(rename = "sst")]
    pub sst: f64,
    #[serde(rename = "xst")]
    pub xst: f64,
    #[serde(rename = "yst")]
    pub yst: f64,
}

#[derive(Debug, Deserialize, Default)]
struct BlSetupRef {
    #[serde(rename = "ist", default)]
    pub ist: usize,
    #[serde(rename = "nbl_upper", default)]
    pub nbl_upper: usize,
    #[serde(rename = "nbl_lower", default)]
    pub nbl_lower: usize,
    #[serde(rename = "iblte_upper", default)]
    pub iblte_upper: usize,
    #[serde(rename = "iblte_lower", default)]
    pub iblte_lower: usize,
}

#[derive(Debug, Deserialize)]
struct ViscousCase {
    alpha_deg: f64,
    alpha_rad: f64,
    #[serde(default)]
    inviscid: InviscidRef,
    stagnation: StagnationRef,
    #[serde(default)]
    bl_setup: BlSetupRef,
    transitions: Vec<TransitionRef>,
    iterations: Vec<IterationRef>,
    #[serde(rename = "final", default)]
    final_result: Option<FinalResultRef>,
    #[serde(default)]
    mrchue_samples: Vec<MrchueRef>,
}

#[derive(Debug, Deserialize, Default)]
struct InviscidRef {
    cl: Option<f64>,
    gam_sample: Option<Vec<f64>>,
    qinv_sample: Option<Vec<f64>>,
}

#[derive(Debug, Deserialize)]
struct TransitionRef {
    side: i32,
    itran: usize,
    x_transition: f64,
    forced: bool,
}

#[derive(Debug, Deserialize)]
struct IterationRef {
    iteration: i32,
    rms_residual: f64,
    max_residual: f64,
    cl: f64,
    cd: f64,
    cm: f64,
}

#[derive(Debug, Deserialize, Default)]
struct FinalResultRef {
    #[serde(default)]
    cl: f64,
    #[serde(default)]
    cd: f64,
    #[serde(default)]
    cm: f64,
    #[serde(default)]
    cd_form: f64,
    #[serde(default)]
    cd_friction: f64,
    #[serde(default)]
    x_tr_upper: f64,
    #[serde(default)]
    x_tr_lower: f64,
    #[serde(default)]
    x_sep_upper: f64,
    #[serde(default)]
    x_sep_lower: f64,
    #[serde(default)]
    iterations: i32,
    #[serde(default)]
    converged: bool,
}

#[derive(Debug, Deserialize)]
struct MrchueRef {
    side: i32,
    ibl: usize,
    x: f64,
    ue: f64,
    theta: f64,
    delta_star: f64,
    hk: f64,
    cf: f64,
    transitional: bool,
}

/// Load viscous reference data from JSON file
fn load_reference() -> Option<ViscousReference> {
    // Build path from CARGO_MANIFEST_DIR (crate root) -> workspace root -> testdata
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").ok()?;
    let workspace_root = Path::new(&manifest_dir).parent()?.parent()?;
    let ref_path = workspace_root.join("testdata").join("viscous_ref.json");
    
    if ref_path.exists() {
        let file = File::open(&ref_path).ok()?;
        let reader = BufReader::new(file);
        return serde_json::from_reader(reader).ok();
    }
    
    // Fallback: try relative paths for running from different directories
    let fallback_paths = [
        Path::new("testdata/viscous_ref.json"),
        Path::new("../../testdata/viscous_ref.json"),
    ];
    
    for path in &fallback_paths {
        if path.exists() {
            let file = File::open(path).ok()?;
            let reader = BufReader::new(file);
            return serde_json::from_reader(reader).ok();
        }
    }
    
    None
}

/// Load NACA 0012 coordinates from XFOIL-generated file
fn load_naca0012_coords() -> Option<Vec<(f64, f64)>> {
    // Build path from CARGO_MANIFEST_DIR
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").ok()?;
    let workspace_root = Path::new(&manifest_dir).parent()?.parent()?;
    let coord_path = workspace_root.join("Xfoil-instrumented/bin/naca0012_xfoil.dat");
    
    let path = if coord_path.exists() {
        coord_path
    } else {
        // Fallback paths
        let fallback_paths = [
            Path::new("Xfoil-instrumented/bin/naca0012_xfoil.dat"),
            Path::new("../../Xfoil-instrumented/bin/naca0012_xfoil.dat"),
        ];
        fallback_paths.iter()
            .find(|p| p.exists())
            .map(|p| p.to_path_buf())?
    };
    
    let content = std::fs::read_to_string(&path).ok()?;
    let coords: Vec<(f64, f64)> = content
        .lines()
        .skip(1) // Skip header
        .filter_map(|line| {
            let parts: Vec<&str> = line.split_whitespace().collect();
            if parts.len() >= 2 {
                let x = parts[0].parse::<f64>().ok()?;
                let y = parts[1].parse::<f64>().ok()?;
                Some((x, y))
            } else {
                None
            }
        })
        .collect();
    
    if !coords.is_empty() {
        Some(coords)
    } else {
        None
    }
}

// ============================================================================
// Test Suite 1: Inviscid Inputs to Viscous Solver
// ============================================================================

#[test]
fn test_inviscid_cl_matches() {
    let ref_data = load_reference();
    if ref_data.is_none() {
        eprintln!("Skipping test: viscous_ref.json not found");
        return;
    }
    let ref_data = ref_data.unwrap();
    
    let coords = load_naca0012_coords();
    if coords.is_none() {
        eprintln!("Skipping test: NACA 0012 coordinates not found");
        return;
    }
    let coords = coords.unwrap();
    
    // Find any case with iterations
    let xfoil_case = ref_data.cases.iter()
        .find(|c| !c.iterations.is_empty());
    
    if xfoil_case.is_none() {
        eprintln!("No case with iterations found in reference data");
        return;
    }
    let xfoil_case = xfoil_case.unwrap();
    
    // Run our inviscid solver
    let result = setup_from_coords(&coords, xfoil_case.alpha_deg);
    assert!(result.is_ok(), "setup_from_coords failed: {:?}", result.err());
    let result = result.unwrap();
    
    let rustfoil_cl = result.inviscid.cl;
    
    // Check if we have pure inviscid CL from reference
    if let Some(ref_cl) = xfoil_case.inviscid.cl {
        // Compare with pure inviscid reference
        let diff_pct = ((rustfoil_cl - ref_cl) / ref_cl * 100.0).abs();
        
        println!("Inviscid CL comparison at α = {}°:", xfoil_case.alpha_deg);
        println!("  XFOIL inviscid: {:.6}", ref_cl);
        println!("  RustFoil:       {:.6}", rustfoil_cl);
        println!("  Difference:     {:.2}%", diff_pct);
        
        assert!(diff_pct < 1.0, 
            "Inviscid CL differs by {:.2}% (XFOIL: {}, RustFoil: {})",
            diff_pct, ref_cl, rustfoil_cl);
    } else {
        // No pure inviscid reference - compare with first viscous iteration
        // Note: Viscous effects reduce CL by ~8-10%, so we use a looser tolerance
        if let Some(first_iter) = xfoil_case.iterations.first() {
            let xfoil_visc_cl = first_iter.cl;
            let diff_pct = ((rustfoil_cl - xfoil_visc_cl) / xfoil_visc_cl * 100.0).abs();
            
            println!("Inviscid CL comparison at α = {}° (vs viscous iter 1):", xfoil_case.alpha_deg);
            println!("  XFOIL (visc iter 1): {:.6}", xfoil_visc_cl);
            println!("  RustFoil (inviscid): {:.6}", rustfoil_cl);
            println!("  Difference:          {:.2}% (expected ~8-10% due to viscous effects)", diff_pct);
            
            // Pure inviscid CL is typically 8-10% higher than viscous CL
            // So RustFoil should be higher than XFOIL viscous iter 1
            assert!(rustfoil_cl > xfoil_visc_cl,
                "Inviscid CL should be higher than viscous CL");
            assert!(diff_pct < 15.0, 
                "Inviscid CL differs by {:.2}% from viscous (expected <15%)",
                diff_pct);
        }
    }
}

#[test]
fn test_stagnation_point_matches() {
    let ref_data = load_reference();
    if ref_data.is_none() {
        eprintln!("Skipping test: viscous_ref.json not found");
        return;
    }
    let ref_data = ref_data.unwrap();
    
    let coords = load_naca0012_coords();
    if coords.is_none() {
        eprintln!("Skipping test: NACA 0012 coordinates not found");
        return;
    }
    let coords = coords.unwrap();
    
    // Find the converged case
    let converged_case = ref_data.cases.iter()
        .find(|c| c.final_result.as_ref().map_or(false, |f| f.converged));
    
    if converged_case.is_none() {
        return;
    }
    let xfoil_case = converged_case.unwrap();
    
    // Run our solver
    let result = setup_from_coords(&coords, xfoil_case.alpha_deg);
    assert!(result.is_ok());
    let result = result.unwrap();
    
    // Compare stagnation point
    let xfoil_stag = &xfoil_case.stagnation;
    
    println!("Stagnation point comparison at α = {}°:", xfoil_case.alpha_deg);
    println!("  XFOIL IST: {}, RustFoil: {}", xfoil_stag.ist, result.ist);
    println!("  XFOIL SST: {:.6}, RustFoil: {:.6}", xfoil_stag.sst, result.sst);
    
    // IST should be within ±2 panels (stagnation point detection is sensitive)
    let ist_diff = (result.ist as i32 - xfoil_stag.ist as i32).abs();
    assert!(ist_diff <= 2, 
        "IST differs by {} (XFOIL: {}, RustFoil: {})", 
        ist_diff, xfoil_stag.ist, result.ist);
    
    // SST should be within 1% of total arc length
    let total_arc = result.setup.arc_lengths.last().copied().unwrap_or(1.0);
    let sst_diff = ((result.sst - xfoil_stag.sst) / total_arc * 100.0).abs();
    assert!(sst_diff < 1.0, 
        "SST differs by {:.2}% of total arc (XFOIL: {}, RustFoil: {})", 
        sst_diff, xfoil_stag.sst, result.sst);
}

// ============================================================================
// Test Suite 2: Surface Extraction
// ============================================================================

#[test]
fn test_surface_counts_match() {
    let ref_data = load_reference();
    if ref_data.is_none() {
        eprintln!("Skipping test: viscous_ref.json not found");
        return;
    }
    let ref_data = ref_data.unwrap();
    
    let coords = load_naca0012_coords();
    if coords.is_none() {
        return;
    }
    let coords = coords.unwrap();
    
    // Run solver at alpha = 4 deg
    let result = setup_from_coords(&coords, 4.0);
    assert!(result.is_ok());
    let result = result.unwrap();
    
    // Count our surfaces
    let n_total = result.setup.arc_lengths.len();
    let n_upper = result.setup.n_upper;
    let n_lower = result.setup.n_lower;
    
    println!("Surface node counts:");
    println!("  Total: {}", n_total);
    println!("  Upper: {}", n_upper);
    println!("  Lower: {}", n_lower);
    println!("  Stagnation index: {}", result.ist);
    
    // Sanity checks
    assert!(n_upper > 0, "Upper surface should have nodes");
    assert!(n_lower > 0, "Lower surface should have nodes");
    assert_eq!(n_upper + n_lower - 1, n_total, 
        "Upper + lower - 1 (stag shared) should equal total");
}

// ============================================================================
// Test Suite 3: Arc Length Computation
// ============================================================================

#[test]
fn test_arc_lengths_positive() {
    let coords = load_naca0012_coords();
    if coords.is_none() {
        return;
    }
    let coords = coords.unwrap();
    
    let x: Vec<f64> = coords.iter().map(|(x, _)| *x).collect();
    let y: Vec<f64> = coords.iter().map(|(_, y)| *y).collect();
    
    let arc = compute_arc_lengths(&x, &y);
    
    // Arc lengths should be monotonically increasing
    for i in 1..arc.len() {
        assert!(arc[i] >= arc[i-1], 
            "Arc length decreased at index {}: {} -> {}", 
            i, arc[i-1], arc[i]);
    }
    
    // First should be 0
    assert!((arc[0] - 0.0).abs() < 1e-10, "First arc length should be 0");
    
    // Total should be > 2 (chord = 1, so perimeter > 2)
    let total = arc.last().copied().unwrap_or(0.0);
    assert!(total > 2.0, "Total arc length {} should be > 2 for unit chord", total);
}

// ============================================================================
// Test Suite 4: MRCHUE Initial BL State - Surface Extraction Validation
// ============================================================================

use rustfoil_solver::viscous::extract_surface_xfoil;

/// Test that surface extraction produces correct arc lengths and Ue values
/// matching XFOIL's IBLPAN + XICALC output.
///
/// This validates the fix to extract_surface_xfoil() which should NOT include
/// the stagnation panel (IST) itself, only panels IST-1 down to 0 for upper surface.
#[test]
fn test_surface_extraction_matches_xfoil() {
    let ref_data = load_reference();
    if ref_data.is_none() {
        eprintln!("Skipping test: viscous_ref.json not found");
        return;
    }
    let ref_data = ref_data.unwrap();
    
    let coords = load_naca0012_coords();
    if coords.is_none() {
        eprintln!("Skipping test: NACA 0012 coordinates not found");
        return;
    }
    let coords = coords.unwrap();
    
    // Find case with MRCHUE samples
    let case = ref_data.cases.iter()
        .find(|c| !c.mrchue_samples.is_empty());
    
    if case.is_none() {
        eprintln!("No MRCHUE samples in reference data");
        return;
    }
    let case = case.unwrap();
    
    // Run our setup
    let result = setup_from_coords(&coords, case.alpha_deg);
    assert!(result.is_ok(), "setup_from_coords failed: {:?}", result.err());
    let result = result.unwrap();
    
    // Extract surfaces using the same function the CLI uses
    let full_arc = &result.setup.arc_lengths;
    let node_x = &result.node_x;
    let node_y = &result.node_y;
    let ue_inviscid = &result.inviscid.gamma;
    let ist = result.ist;
    let sst = result.sst;
    
    // Interpolate Ue at stagnation
    let ue_stag = if ist + 1 < ue_inviscid.len() && full_arc[ist + 1] != full_arc[ist] {
        let frac = (sst - full_arc[ist]) / (full_arc[ist + 1] - full_arc[ist]);
        ue_inviscid[ist] + frac * (ue_inviscid[ist + 1] - ue_inviscid[ist])
    } else {
        ue_inviscid[ist]
    };
    
    let (upper_arc, _upper_x, _upper_y, upper_ue) = extract_surface_xfoil(
        ist, sst, ue_stag, full_arc, node_x, node_y, ue_inviscid, true
    );
    
    println!("\nSurface extraction results:");
    println!("  IST = {}, SST = {:.6}", ist, sst);
    println!("  Upper surface: {} stations", upper_arc.len());
    println!("  Station 0 (virtual stag): arc={:.6}, Ue={:.6}", upper_arc[0], upper_ue[0]);
    
    // Compare with XFOIL MRCHUE samples (side=1 is upper surface)
    let upper_samples: Vec<_> = case.mrchue_samples.iter()
        .filter(|s| s.side == 1)
        .collect();
    
    if upper_samples.is_empty() {
        eprintln!("No upper surface samples in reference data");
        return;
    }
    
    println!("\nComparison with XFOIL MRCHUE (first 5 stations):");
    println!("{:>4} {:>12} {:>12} {:>12} {:>12} {:>10}", 
        "IBL", "XFOIL arc", "Rust arc", "XFOIL Ue", "Rust Ue", "arc err%");
    
    // IBL=2 in XFOIL corresponds to index 1 in our array (index 0 is virtual stagnation)
    for sample in upper_samples.iter().take(5) {
        let rust_idx = sample.ibl - 1; // IBL is 1-indexed, our array is 0-indexed
        
        if rust_idx >= upper_arc.len() {
            eprintln!("  IBL {} out of range (have {} stations)", sample.ibl, upper_arc.len());
            continue;
        }
        
        let rust_arc = upper_arc[rust_idx];
        let rust_ue = upper_ue[rust_idx];
        let xfoil_arc = sample.x;
        let xfoil_ue = sample.ue;
        
        let arc_err = if xfoil_arc > 1e-10 {
            ((rust_arc - xfoil_arc) / xfoil_arc * 100.0).abs()
        } else {
            0.0
        };
        
        println!("{:>4} {:>12.6} {:>12.6} {:>12.6} {:>12.6} {:>9.1}%", 
            sample.ibl, xfoil_arc, rust_arc, xfoil_ue, rust_ue, arc_err);
    }
    
    // Check that station 2 (IBL=2, index 1) arc length is close to XFOIL
    // XFOIL IBL=2 has x ≈ 0.0011
    if let Some(sample2) = upper_samples.iter().find(|s| s.ibl == 2) {
        let rust_arc = upper_arc.get(1).copied().unwrap_or(0.0);
        let rust_ue = upper_ue.get(1).copied().unwrap_or(0.0);
        
        let arc_diff_pct = ((rust_arc - sample2.x) / sample2.x * 100.0).abs();
        let ue_diff_pct = ((rust_ue - sample2.ue) / sample2.ue * 100.0).abs();
        
        println!("\nStation 2 (IBL=2) validation:");
        println!("  Arc: XFOIL={:.6}, RustFoil={:.6}, diff={:.1}%", 
            sample2.x, rust_arc, arc_diff_pct);
        println!("  Ue:  XFOIL={:.6}, RustFoil={:.6}, diff={:.1}%", 
            sample2.ue, rust_ue, ue_diff_pct);
        
        // Arc length should be within 50% (we're validating the fix worked)
        // A 100x error (which existed before) will clearly fail this
        assert!(arc_diff_pct < 50.0, 
            "Station 2 arc differs by {:.1}% (XFOIL: {}, RustFoil: {}). \
            This suggests extract_surface_xfoil is not excluding the stagnation panel.",
            arc_diff_pct, sample2.x, rust_arc);
        
        // Ue should be within order of magnitude
        assert!(ue_diff_pct < 100.0,
            "Station 2 Ue differs by {:.1}% (XFOIL: {}, RustFoil: {})",
            ue_diff_pct, sample2.ue, rust_ue);
    }
}

#[test]
#[ignore = "Requires full viscous solve implementation"]
fn test_mrchue_initial_theta() {
    // This test will compare initial boundary layer theta values
    // from XFOIL's MRCHUE with our march_fixed_ue
    
    let ref_data = load_reference();
    if ref_data.is_none() {
        return;
    }
    let ref_data = ref_data.unwrap();
    
    // Find converged case with MRCHUE samples
    let case = ref_data.cases.iter()
        .find(|c| !c.mrchue_samples.is_empty());
    
    if case.is_none() {
        eprintln!("No MRCHUE samples in reference data");
        return;
    }
    
    let case = case.unwrap();
    println!("Reference MRCHUE samples (first 5):");
    for sample in case.mrchue_samples.iter().take(5) {
        println!("  ibl={}: x={:.6}, ue={:.4}, theta={:.2e}, H={:.3}",
            sample.ibl, sample.x, sample.ue, sample.theta, sample.hk);
    }
    
    // TODO: Run our BL march and compare theta values
}

// ============================================================================
// Test Suite 5: Final Aerodynamic Coefficients (placeholder)
// ============================================================================

#[test]
#[ignore = "Requires full viscous solve implementation"]
fn test_final_cl_cd_cm() {
    // This test will compare final CL, CD, CM after viscous iteration
    
    let ref_data = load_reference();
    if ref_data.is_none() {
        return;
    }
    let ref_data = ref_data.unwrap();
    
    // Find converged case
    let case = ref_data.cases.iter()
        .find(|c| c.final_result.as_ref().map_or(false, |f| f.converged));
    
    if case.is_none() {
        return;
    }
    
    let case = case.unwrap();
    let final_result = case.final_result.as_ref().unwrap();
    
    println!("XFOIL final results at α = {}°:", case.alpha_deg);
    println!("  CL = {:.4}", final_result.cl);
    println!("  CD = {:.5}", final_result.cd);
    println!("  CM = {:.4}", final_result.cm);
    println!("  x_tr upper = {:.4}", final_result.x_tr_upper);
    println!("  x_tr lower = {:.4}", final_result.x_tr_lower);
    
    // TODO: Run full viscous solve and compare
}

// ============================================================================
// Utility Tests
// ============================================================================

#[test]
fn test_reference_data_loads() {
    let ref_data = load_reference();
    
    if ref_data.is_none() {
        eprintln!("Note: Reference data not found. Run:");
        eprintln!("  python scripts/extract_viscous_reference.py");
        return;
    }
    
    let ref_data = ref_data.unwrap();
    
    println!("Loaded reference data:");
    println!("  Source: {}", ref_data.source);
    println!("  Airfoil: {}", ref_data.airfoil);
    println!("  Panels: {}", ref_data.n_panels);
    println!("  Reynolds: {:.2e}", ref_data.reynolds);
    println!("  Cases: {}", ref_data.cases.len());
    
    // Find converged case
    let converged = ref_data.cases.iter()
        .filter(|c| c.final_result.as_ref().map_or(false, |f| f.converged))
        .count();
    println!("  Converged cases: {}", converged);
}

#[test]
fn test_naca0012_coords_load() {
    let coords = load_naca0012_coords();
    
    if coords.is_none() {
        eprintln!("Note: NACA 0012 coordinate file not found.");
        eprintln!("Generate with XFOIL: NACA 0012, SAVE");
        return;
    }
    
    let coords = coords.unwrap();
    println!("Loaded NACA 0012 coordinates: {} points", coords.len());
    
    // Basic validation
    assert!(coords.len() >= 50, "Should have at least 50 points");
    
    // Should start and end near x=1 (TE)
    let (first_x, _) = coords.first().unwrap();
    let (last_x, _) = coords.last().unwrap();
    assert!(*first_x > 0.99, "First point should be near TE");
    assert!(*last_x > 0.99, "Last point should be near TE");
    
    // Should have LE near x=0
    let has_le = coords.iter().any(|(x, _)| *x < 0.01);
    assert!(has_le, "Should have points near leading edge");
}
